"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import {
  Analytics,
  CONTENT_TYPES,
  ContentAsset,
  exportFiles,
  groupCount,
  isWorkspace,
  MARKETING_OBJECTIVES,
  makeBenchmark,
  MessagingStrategy,
  REUSE_CONTEXTS,
  ReviewStatus,
  Solution,
  Workspace,
  applyContentEdit,
  applyReuse,
  applyReviewDecision,
  buildDemoWorkspace,
  calculateAnalytics,
  createStrategy,
  generateDemoCopy,
} from "./lib/echoflow";

type Page = "Dashboard" | "Solutions" | "Generate" | "Content Library" | "Review" | "Analytics" | "Benchmark" | "Settings";

const navItems: { page: Page; icon: string }[] = [
  { page: "Dashboard", icon: "◫" }, { page: "Solutions", icon: "◇" }, { page: "Generate", icon: "✦" },
  { page: "Content Library", icon: "▤" }, { page: "Review", icon: "✓" }, { page: "Analytics", icon: "↗" },
  { page: "Benchmark", icon: "◷" }, { page: "Settings", icon: "⚙" },
];

const statusLabels: Record<ReviewStatus, string> = { draft: "Draft", in_review: "In review", approved: "Approved", rejected: "Rejected", final: "Final" };

function percent(value: number) { return `${value.toFixed(1)}%`; }
function minutes(value: number) { return `${value.toFixed(1)} min`; }
function download(name: string, body: string, type = "text/csv;charset=utf-8") {
  const url = URL.createObjectURL(new Blob(["\ufeff", body], { type }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url);
}

function KpiCard({ label, value, note, accent = "indigo" }: { label: string; value: string | number; note: string; accent?: string }) {
  return <article className={`kpi-card ${accent}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>;
}

function PageHeader({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: React.ReactNode }) {
  return <header className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{actions && <div className="heading-actions">{actions}</div>}</header>;
}

function MetricBar({ label, value, max, suffix = "" }: { label: string; value: number; max: number; suffix?: string }) {
  return <div className="metric-row"><div><span>{label}</span><strong>{value}{suffix}</strong></div><div className="metric-track"><i style={{ width: `${Math.max(3, (value / Math.max(max, 1)) * 100)}%` }} /></div></div>;
}

function Dashboard({ workspace, analytics, setPage }: { workspace: Workspace; analytics: Analytics; setPage: (page: Page) => void }) {
  const bySolution = groupCount(workspace.assets, (asset) => workspace.solutions.find((solution) => solution.solution_id === asset.solution_id)?.solution_name ?? asset.solution_id).slice(0, 5);
  const byStakeholder = groupCount(workspace.assets, (asset) => workspace.stakeholders.find((stakeholder) => stakeholder.stakeholder_id === asset.stakeholder_id)?.name ?? asset.stakeholder_id);
  return <>
    <section className="hero-panel">
      <div className="hero-copy"><span className="hero-kicker">AI-ASSISTED SOLUTION MARKETING OPERATIONS</span><h1>Turn complex solutions into stakeholder-ready content.</h1><p>EchoFlow helps marketing teams transform smart-city and digital-government solution information into evidence-conscious marketing and sales-support assets.</p><div className="hero-actions"><button className="primary" onClick={() => setPage("Generate")}>Create content <b>→</b></button><button className="secondary" onClick={() => setPage("Solutions")}>Browse solutions</button></div></div>
      <div className="workflow-card"><span>STANDARD WORKFLOW</span>{["Solution", "Stakeholder", "Messaging", "AI draft", "Human review", "Reuse"].map((item, index) => <div key={item}><b>{String(index + 1).padStart(2, "0")}</b><strong>{item}</strong>{index < 5 && <i>↓</i>}</div>)}</div>
    </section>
    <section className="kpi-grid four"><KpiCard label="Managed solutions" value={analytics.solution_count} note="Fictional demo solution records"/><KpiCard label="Stakeholder segments" value={analytics.stakeholder_count} note="Reusable audience profiles" accent="blue"/><KpiCard label="Content assets" value={analytics.content_asset_count} note="Generated workspace records" accent="teal"/><KpiCard label="First-pass approval" value={percent(analytics.first_pass_approval_rate)} note={`${analytics.reviewed_asset_count} reviewed assets`} accent="amber"/></section>
    <section className="two-columns">
      <article className="panel efficiency-panel"><div className="panel-title"><div><span>EFFICIENCY</span><h2>Adaptation workflow</h2></div><button className="text-button" onClick={() => setPage("Benchmark")}>View benchmark →</button></div><div className="comparison"><div><span>Manual average</span><strong>{minutes(analytics.manual_adaptation_time)}</strong><i className="manual-line" /></div><div><span>EchoFlow average</span><strong>{minutes(analytics.ai_adaptation_time)}</strong><i className="ai-line" style={{ width: `${Math.min(100, (analytics.ai_adaptation_time / Math.max(analytics.manual_adaptation_time, 1)) * 100)}%` }} /></div></div><div className="saving-callout"><b>{percent(analytics.time_reduction_rate)}</b><span>average time reduction<br/><small>Generation + review + editing are included.</small></span></div></article>
      <article className="panel"><div className="panel-title"><div><span>CONTENT PERFORMANCE</span><h2>Human-review outcomes</h2></div><button className="text-button" onClick={() => setPage("Analytics")}>Open analytics →</button></div><div className="performance-grid"><div><strong>{percent(analytics.first_pass_approval_rate)}</strong><span>First-pass approval</span></div><div><strong>{percent(analytics.content_reuse_rate)}</strong><span>Approved-asset reuse</span></div><div><strong>{analytics.average_edit_count}</strong><span>Average edit count</span></div><div><strong>{minutes(analytics.average_review_time_minutes)}</strong><span>Average review time</span></div></div></article>
    </section>
    <section className="two-columns">
      <article className="panel"><div className="panel-title"><div><span>PORTFOLIO</span><h2>Assets by solution</h2></div></div><div className="metric-list">{bySolution.map((item) => <MetricBar key={item.label} {...item} max={Math.max(...bySolution.map((entry) => entry.value))}/>)}</div></article>
      <article className="panel"><div className="panel-title"><div><span>SEGMENTS</span><h2>Assets by stakeholder</h2></div></div><div className="metric-list">{byStakeholder.map((item) => <MetricBar key={item.label} {...item} max={Math.max(...byStakeholder.map((entry) => entry.value))}/>)}</div></article>
    </section>
  </>;
}

function SolutionsView({ workspace, update }: { workspace: Workspace; update: (fn: (value: Workspace) => Workspace, message: string) => void }) {
  const [query, setQuery] = useState(""); const [showForm, setShowForm] = useState(false); const [selected, setSelected] = useState(workspace.solutions[0]?.solution_id ?? "");
  const filtered = workspace.solutions.filter((solution) => `${solution.solution_name} ${solution.solution_category} ${solution.short_description}`.toLowerCase().includes(query.toLowerCase()));
  const active = workspace.solutions.find((solution) => solution.solution_id === selected) ?? filtered[0];
  function createSolutionRecord(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const now = new Date().toISOString();
    const record: Solution = { solution_id: `SOL-${Date.now()}`, solution_name: String(data.get("name") ?? "").trim(), solution_category: String(data.get("category") ?? "").trim(), short_description: String(data.get("description") ?? "").trim(), business_problem: String(data.get("problem") ?? "").trim(), key_capabilities: String(data.get("capabilities") ?? "").split("\n").filter(Boolean), target_users: String(data.get("users") ?? "").split("\n").filter(Boolean), business_value: String(data.get("value") ?? "").split("\n").filter(Boolean), technical_highlights: String(data.get("technical") ?? "").split("\n").filter(Boolean), implementation_context: String(data.get("context") ?? "").trim(), source_reference: String(data.get("source") ?? "").trim() || "User-supplied workspace record", created_at: now, updated_at: now };
    if (!record.solution_name || !record.solution_category || !record.short_description || !record.business_problem || !record.key_capabilities.length) return;
    update((value) => ({ ...value, solutions: [record, ...value.solutions] }), "Solution added to the library."); setShowForm(false); setSelected(record.solution_id); event.currentTarget.reset();
  }
  return <><PageHeader eyebrow="Solution intelligence" title="Solution Library" description="Create an evidence-backed source record once, then adapt its value for different stakeholders." actions={<><label className="search"><span>⌕</span><input aria-label="Search solutions" placeholder="Search solutions" value={query} onChange={(event) => setQuery(event.target.value)}/></label><button className="primary" onClick={() => setShowForm(true)}>+ Add solution</button></>}/>
    <div className="library-layout"><aside className="solution-list"><div className="list-caption"><span>{filtered.length} solutions</span><small>Demo records are clearly labelled</small></div>{filtered.map((solution) => <button key={solution.solution_id} className={active?.solution_id === solution.solution_id ? "active" : ""} onClick={() => setSelected(solution.solution_id)}><i>{solution.solution_category.slice(0, 2).toUpperCase()}</i><span><strong>{solution.solution_name}</strong><small>{solution.solution_category}</small></span><b>›</b></button>)}</aside>
      {active && <article className="solution-detail"><div className="detail-header"><div><span className="category-pill">{active.solution_category}</span><h2>{active.solution_name}</h2><p>{active.short_description}</p></div><span className="demo-badge">FICTIONAL DEMO</span></div><div className="detail-grid"><section><span>BUSINESS PROBLEM</span><p>{active.business_problem}</p></section><section><span>IMPLEMENTATION CONTEXT</span><p>{active.implementation_context}</p></section><section><span>KEY CAPABILITIES</span><ul>{active.key_capabilities.map((item) => <li key={item}>{item}</li>)}</ul></section><section><span>BUSINESS VALUE</span><ul>{active.business_value.map((item) => <li key={item}>{item}</li>)}</ul></section><section><span>TECHNICAL HIGHLIGHTS</span><ul>{active.technical_highlights.map((item) => <li key={item}>{item}</li>)}</ul></section><section><span>TARGET USERS</span><ul>{active.target_users.map((item) => <li key={item}>{item}</li>)}</ul></section></div><footer><span>Source reference</span><p>{active.source_reference}</p></footer></article>}</div>
    {showForm && <div className="modal-backdrop" onMouseDown={() => setShowForm(false)}><form className="modal solution-form" onSubmit={createSolutionRecord} onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><span>NEW SOURCE RECORD</span><h2>Add a solution</h2></div><button type="button" onClick={() => setShowForm(false)}>×</button></div><div className="form-grid"><label>Name<input name="name" required/></label><label>Category<input name="category" required/></label><label className="wide">Short description<textarea name="description" required/></label><label className="wide">Business problem<textarea name="problem" required/></label><label>Key capabilities <small>One per line</small><textarea name="capabilities" required/></label><label>Business value <small>One per line</small><textarea name="value" required/></label><label>Target users<textarea name="users"/></label><label>Technical highlights<textarea name="technical"/></label><label className="wide">Implementation context<textarea name="context"/></label><label className="wide">Source reference<input name="source" placeholder="Document, interview or user-supplied source"/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={() => setShowForm(false)}>Cancel</button><button className="primary">Save solution</button></div></form></div>}
  </>;
}

function GenerateView({ workspace, update, setPage }: { workspace: Workspace; update: (fn: (value: Workspace) => Workspace, message: string) => void; setPage: (page: Page) => void }) {
  const [solutionId, setSolutionId] = useState(workspace.solutions[0]?.solution_id ?? ""); const [stakeholderId, setStakeholderId] = useState(workspace.stakeholders[0]?.stakeholder_id ?? ""); const [objective, setObjective] = useState<string>(MARKETING_OBJECTIVES[0]); const [contentType, setContentType] = useState<string>(CONTENT_TYPES[0]); const [strategy, setStrategy] = useState<MessagingStrategy | null>(() => workspace.solutions[0] && workspace.stakeholders[0] ? createStrategy(workspace.solutions[0], workspace.stakeholders[0], MARKETING_OBJECTIVES[0], CONTENT_TYPES[0]) : null); const [busy, setBusy] = useState(false);
  const solution = workspace.solutions.find((item) => item.solution_id === solutionId); const stakeholder = workspace.stakeholders.find((item) => item.stakeholder_id === stakeholderId);
  useEffect(() => { const next = solution && stakeholder ? createStrategy(solution, stakeholder, objective, contentType) : null; queueMicrotask(() => setStrategy(next)); }, [solution, stakeholder, objective, contentType]);
  function editStrategy(field: keyof MessagingStrategy, value: string) { setStrategy((current) => current ? { ...current, [field]: value } : current); }
  async function generate() {
    if (!solution || !stakeholder || !strategy || !strategy.core_value_proposition.trim()) return; setBusy(true); const started = performance.now(); let result = generateDemoCopy(solution, stakeholder, strategy); let mode: "demo" | "api" = "demo";
    try { const response = await fetch("/api/generate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ solution, stakeholder, strategy, requestedMode: workspace.settings.generation_mode }) }); if (response.ok) { const payload = await response.json() as { title: string; content: string; mode: "demo" | "api" }; result = { title: payload.title, content: payload.content }; mode = payload.mode; } } catch { /* deterministic fallback remains available */ }
    const now = new Date().toISOString(); const id = `AST-${Date.now()}`; const asset: ContentAsset = { draft_id: id, solution_id: solution.solution_id, stakeholder_id: stakeholder.stakeholder_id, content_type: contentType, marketing_objective: objective, title: result.title, content: result.content, generated_at: now, generation_seconds: Number(Math.max((performance.now() - started) / 1000, 0.1).toFixed(1)), generation_mode: mode, review_status: "in_review", approved_first_pass: null, edit_count: 0, review_time_minutes: 0, finalised_at: null, reuse_count: 0, reuse_context: [], version: 1 };
    update((value) => ({ ...value, strategies: [strategy, ...value.strategies], assets: [asset, ...value.assets], reviews: [{ review_id: `REV-${Date.now()}`, draft_id: id, action: "submitted", occurred_at: now, duration_minutes: 0, note: "Submitted for human review." }, ...value.reviews] }), `${mode === "api" ? "API" : "Demo"} draft generated and sent to review.`); setBusy(false); setPage("Review");
  }
  return <><PageHeader eyebrow="Guided generation" title="Create stakeholder-specific content" description="Build and review the message architecture before generating a guarded draft."/><div className="generate-layout"><section className="panel generator-controls"><div className="step-heading"><b>01</b><div><h2>Set the brief</h2><p>Four inputs define the content context.</p></div></div><label>Solution<select value={solutionId} onChange={(event) => setSolutionId(event.target.value)}>{workspace.solutions.map((item) => <option key={item.solution_id} value={item.solution_id}>{item.solution_name}</option>)}</select></label><label>Stakeholder<select value={stakeholderId} onChange={(event) => setStakeholderId(event.target.value)}>{workspace.stakeholders.map((item) => <option key={item.stakeholder_id} value={item.stakeholder_id}>{item.name}</option>)}</select></label><label>Marketing objective<select value={objective} onChange={(event) => setObjective(event.target.value)}>{MARKETING_OBJECTIVES.map((item) => <option key={item}>{item}</option>)}</select></label><label>Content type<select value={contentType} onChange={(event) => setContentType(event.target.value)}>{CONTENT_TYPES.map((item) => <option key={item}>{item}</option>)}</select></label>{stakeholder && <div className="stakeholder-card"><span>{stakeholder.technical_depth} technical depth</span><strong>{stakeholder.name}</strong><p>Prioritise {stakeholder.messaging_priority.join(", ").toLowerCase()}.</p><small>Risk focus: {stakeholder.risk_concerns.join(" · ")}</small></div>}</section>
      <section className="panel strategy-editor"><div className="step-heading"><b>02</b><div><h2>Review messaging strategy</h2><p>Edit every field before content generation.</p></div><span className="editable-badge">EDITABLE</span></div>{strategy && <div className="strategy-fields"><label>Core value proposition<textarea value={strategy.core_value_proposition} onChange={(event) => editStrategy("core_value_proposition", event.target.value)}/></label><label>Three key messages<textarea value={strategy.key_messages.join("\n")} onChange={(event) => setStrategy({ ...strategy, key_messages: event.target.value.split("\n").filter(Boolean) })}/></label><label>Supporting proof points<textarea value={strategy.supporting_proof_points.join("\n")} onChange={(event) => setStrategy({ ...strategy, supporting_proof_points: event.target.value.split("\n").filter(Boolean) })}/></label><div className="field-pair"><label>Recommended tone<input value={strategy.recommended_tone} onChange={(event) => editStrategy("recommended_tone", event.target.value)}/></label><label>CTA<input value={strategy.cta} onChange={(event) => editStrategy("cta", event.target.value)}/></label></div><label>Content angle<input value={strategy.content_angle} onChange={(event) => editStrategy("content_angle", event.target.value)}/></label></div>}<div className="guardrail-box"><b>✓ Evidence guardrails active</b><p>No invented statistics, partnerships, clients or technical capabilities. Generated marketing language is labelled separately from supplied facts.</p></div><button className="generate-cta" disabled={busy || !strategy?.core_value_proposition.trim()} onClick={generate}><span>✦</span><div><strong>{busy ? "Generating evidence-conscious draft…" : "Generate content draft"}</strong><small>{workspace.settings.generation_mode === "demo" ? "Deterministic Demo Mode — no API key required" : "API mode with automatic Demo Mode fallback"}</small></div><b>→</b></button></section></div></>;
}

function AssetTable({ workspace, assets, actions }: { workspace: Workspace; assets: ContentAsset[]; actions?: (asset: ContentAsset) => React.ReactNode }) {
  return <div className="table-wrap"><table><thead><tr><th>Asset</th><th>Solution / stakeholder</th><th>Type</th><th>Status</th><th>Edits</th><th>Reuse</th>{actions && <th>Actions</th>}</tr></thead><tbody>{assets.map((asset) => { const solution = workspace.solutions.find((item) => item.solution_id === asset.solution_id); const stakeholder = workspace.stakeholders.find((item) => item.stakeholder_id === asset.stakeholder_id); return <tr key={asset.draft_id}><td><strong>{asset.title}</strong><small>{asset.draft_id} · V{asset.version} · {asset.generation_mode}</small></td><td><span>{solution?.solution_name}</span><small>{stakeholder?.name}</small></td><td>{asset.content_type}</td><td><span className={`status ${asset.review_status}`}>{statusLabels[asset.review_status]}</span></td><td>{asset.edit_count}</td><td>{asset.reuse_count}</td>{actions && <td><div className="row-actions">{actions(asset)}</div></td>}</tr>; })}</tbody></table>{!assets.length && <div className="empty"><b>No matching assets</b><span>Change the filter or generate a new draft.</span></div>}</div>;
}

function LibraryView({ workspace }: { workspace: Workspace }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all");
  const assets = workspace.assets.filter((asset) => (status === "all" || asset.review_status === status) && `${asset.title} ${asset.content_type}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader eyebrow="Content operations" title="Content Library" description="Search every generated asset, its review outcome, edit history and reuse record." actions={<button className="primary" onClick={() => download("content_assets.csv", exportFiles(workspace)["content_assets.csv"])}>Export assets</button>}/><div className="filter-bar"><label className="search grow"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title or content type"/></label><select aria-label="Filter by status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><span className="record-count">{assets.length} records</span></div><AssetTable workspace={workspace} assets={assets}/></>;
}

function ReviewView({ workspace, update }: { workspace: Workspace; update: (fn: (value: Workspace) => Workspace, message: string) => void }) {
  const [filter, setFilter] = useState<ReviewStatus | "all">("in_review"); const [editing, setEditing] = useState<ContentAsset | null>(null); const [reuseContext, setReuseContext] = useState<string>(REUSE_CONTEXTS[0]);
  const assets = workspace.assets.filter((asset) => filter === "all" || asset.review_status === filter).slice(0, 40);
  function transition(asset: ContentAsset, status: ReviewStatus, action: "approved" | "rejected" | "finalised") { update((value) => applyReviewDecision(value, asset.draft_id, action), `Asset marked ${statusLabels[status].toLowerCase()}.`); }
  function saveEdit() { if (!editing || !editing.title.trim() || !editing.content.trim()) return; update((value) => applyContentEdit(value, editing.draft_id, editing.title, editing.content), "Edits saved and review history updated."); setEditing(null); }
  function regenerate(asset: ContentAsset) { const solution = workspace.solutions.find((item) => item.solution_id === asset.solution_id); const stakeholder = workspace.stakeholders.find((item) => item.stakeholder_id === asset.stakeholder_id); if (!solution || !stakeholder) return; const strategy = workspace.strategies.find((item) => item.solution_id === asset.solution_id && item.stakeholder_id === asset.stakeholder_id) ?? createStrategy(solution, stakeholder, asset.marketing_objective, asset.content_type); const copy = generateDemoCopy(solution, stakeholder, strategy); const now = new Date().toISOString(); update((value) => ({ ...value, assets: value.assets.map((item) => item.draft_id === asset.draft_id ? { ...item, ...copy, version: item.version + 1, edit_count: item.edit_count + 1, review_status: "in_review", approved_first_pass: item.approved_first_pass ?? false, generated_at: now } : item), reviews: [{ review_id: `REV-${Date.now()}`, draft_id: asset.draft_id, action: "regenerated", occurred_at: now, duration_minutes: 0, note: "Regenerated in deterministic Demo Mode." }, ...value.reviews] }), "A new demo version was generated."); }
  function markReuse(asset: ContentAsset) { update((value) => applyReuse(value, asset.draft_id, reuseContext), `Reuse recorded for ${reuseContext}.`); }
  return <><PageHeader eyebrow="Human-in-the-loop" title="Review queue" description="Approve, reject, edit, regenerate and finalise content. Every action updates the traceable workflow record." actions={<div className="reuse-control"><select value={reuseContext} onChange={(event) => setReuseContext(event.target.value)}>{REUSE_CONTEXTS.map((item) => <option key={item}>{item}</option>)}</select><small>Reuse context</small></div>}/><div className="status-tabs">{(["all", "in_review", "approved", "rejected", "final"] as const).map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item === "all" ? "All" : statusLabels[item]} <b>{item === "all" ? workspace.assets.length : workspace.assets.filter((asset) => asset.review_status === item).length}</b></button>)}</div><AssetTable workspace={workspace} assets={assets} actions={(asset) => <>{asset.review_status === "in_review" && <><button className="small positive" onClick={() => transition(asset, "approved", "approved")}>Approve</button><button className="small danger" onClick={() => transition(asset, "rejected", "rejected")}>Reject</button></>}<button className="small" onClick={() => setEditing(asset)}>Edit</button><button className="small" onClick={() => regenerate(asset)}>Regenerate</button>{asset.review_status === "approved" && <button className="small positive" onClick={() => transition(asset, "final", "finalised")}>Finalise</button>}{(asset.review_status === "approved" || asset.review_status === "final") && <button className="small reuse" onClick={() => markReuse(asset)}>Mark reused</button>}</>}/>
    {editing && <div className="modal-backdrop" onMouseDown={() => setEditing(null)}><section className="modal editor" onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><span>HUMAN REVIEW · {editing.draft_id}</span><h2>Edit content</h2></div><button onClick={() => setEditing(null)}>×</button></div><label>Title<input value={editing.title} onChange={(event) => setEditing({ ...editing, title: event.target.value })}/></label><label>Content<textarea value={editing.content} onChange={(event) => setEditing({ ...editing, content: event.target.value })}/></label><div className="evidence-note">Edits create a new version and make this asset ineligible for first-pass approval.</div><div className="modal-actions"><button className="secondary" onClick={() => setEditing(null)}>Cancel</button><button className="primary" onClick={saveEdit}>Save as V{editing.version + 1}</button></div></section></div>}
  </>;
}

function AnalyticsView({ workspace, analytics }: { workspace: Workspace; analytics: Analytics }) {
  const contentTypes = groupCount(workspace.assets, (asset) => asset.content_type); const stakeholders = groupCount(workspace.assets, (asset) => workspace.stakeholders.find((item) => item.stakeholder_id === asset.stakeholder_id)?.name ?? asset.stakeholder_id); const maxType = Math.max(...contentTypes.map((item) => item.value));
  return <><PageHeader eyebrow="Source-backed performance" title="Analytics" description="Every number below is recalculated from workspace content, review, reuse and benchmark records." actions={<button className="primary" onClick={() => download("analytics_summary.csv", exportFiles(workspace)["analytics_summary.csv"])}>Export summary</button>}/><div className="provenance-banner"><span>✓</span><div><strong>Live calculation</strong><p>No result KPI is hardcoded. Current sample: {workspace.assets.length} assets, {analytics.reviewed_asset_count} reviewed records and {workspace.benchmarks.length} complete workflow benchmarks.</p></div></div><section className="kpi-grid four"><KpiCard label="Approved assets" value={analytics.approved_asset_count} note="approved + final records"/><KpiCard label="First-pass approval" value={percent(analytics.first_pass_approval_rate)} note="first-pass approved ÷ reviewed" accent="blue"/><KpiCard label="Content reuse rate" value={percent(analytics.content_reuse_rate)} note="approved reused ÷ approved" accent="teal"/><KpiCard label="Average edits" value={analytics.average_edit_count} note="edit count ÷ all assets" accent="amber"/></section><section className="kpi-grid four"><KpiCard label="Generation time" value={`${analytics.average_generation_time_seconds}s`} note="average recorded generation"/><KpiCard label="Review time" value={minutes(analytics.average_review_time_minutes)} note="average reviewed asset" accent="blue"/><KpiCard label="Manual adaptation" value={minutes(analytics.manual_adaptation_time)} note="average benchmark baseline" accent="teal"/><KpiCard label="Time reduction" value={percent(analytics.time_reduction_rate)} note="average row-level reduction" accent="amber"/></section><section className="two-columns"><article className="panel"><div className="panel-title"><div><span>BREAKDOWN</span><h2>Assets by content type</h2></div></div><div className="metric-list dense">{contentTypes.map((item) => <MetricBar key={item.label} {...item} max={maxType}/>)}</div></article><article className="panel"><div className="panel-title"><div><span>BREAKDOWN</span><h2>Assets by stakeholder</h2></div></div><div className="segment-list">{stakeholders.map((item) => <div key={item.label}><span><i>{item.label.slice(0, 2).toUpperCase()}</i><strong>{item.label}</strong></span><b>{item.value}</b></div>)}</div><div className="formula-box"><span>CORE FORMULAS</span><code>First-pass approval = approved_first_pass / reviewed assets</code><code>Reuse rate = approved assets reused ≥ 1 / approved assets</code><code>AI time = generation + review + editing</code></div></article></section></>;
}

function BenchmarkView({ workspace, analytics, update }: { workspace: Workspace; analytics: Analytics; update: (fn: (value: Workspace) => Workspace, message: string) => void }) {
  const [solutionId, setSolutionId] = useState(workspace.solutions[0]?.solution_id ?? ""); const [stakeholderId, setStakeholderId] = useState(workspace.stakeholders[0]?.stakeholder_id ?? ""); const [contentType, setContentType] = useState<string>(CONTENT_TYPES[0]);
  function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const numbers = ["manual", "generation", "review", "edit"].map((key) => Number(data.get(key))); if (numbers.some((value) => !Number.isFinite(value) || value < 0) || numbers[0] <= 0) return; const record = makeBenchmark({ benchmark_id: `BM-${Date.now()}`, solution_id: solutionId, stakeholder_id: stakeholderId, content_type: contentType, manual_minutes: numbers[0], ai_generation_minutes: numbers[1], ai_review_minutes: numbers[2], ai_edit_minutes: numbers[3], timestamp: new Date().toISOString() }); update((value) => ({ ...value, benchmarks: [record, ...value.benchmarks] }), `Benchmark saved: ${record.time_reduction_percentage}% time reduction.`); event.currentTarget.reset(); }
  return <><PageHeader eyebrow="Workflow measurement" title="Manual vs EchoFlow benchmark" description="Compare complete workflows—not only model generation speed. Review and editing time are always included." actions={<button className="primary" onClick={() => download("benchmarks.csv", exportFiles(workspace)["benchmarks.csv"])}>Export benchmark</button>}/><section className="kpi-grid three"><KpiCard label="Average manual time" value={minutes(analytics.manual_adaptation_time)} note={`${workspace.benchmarks.length} benchmark rows`}/><KpiCard label="Average EchoFlow time" value={minutes(analytics.ai_adaptation_time)} note="generation + review + edit" accent="blue"/><KpiCard label="Average reduction" value={percent(analytics.time_reduction_rate)} note="mean row-level reduction" accent="teal"/></section><section className="benchmark-layout"><form className="panel benchmark-form" onSubmit={add}><div className="panel-title"><div><span>NEW OBSERVATION</span><h2>Record a benchmark</h2></div></div><label>Solution<select value={solutionId} onChange={(event) => setSolutionId(event.target.value)}>{workspace.solutions.map((item) => <option key={item.solution_id} value={item.solution_id}>{item.solution_name}</option>)}</select></label><label>Stakeholder<select value={stakeholderId} onChange={(event) => setStakeholderId(event.target.value)}>{workspace.stakeholders.map((item) => <option key={item.stakeholder_id} value={item.stakeholder_id}>{item.name}</option>)}</select></label><label>Content type<select value={contentType} onChange={(event) => setContentType(event.target.value)}>{CONTENT_TYPES.map((item) => <option key={item}>{item}</option>)}</select></label><div className="time-inputs"><label>Manual minutes<input name="manual" type="number" min="0.1" step="0.1" required/></label><label>Generation<input name="generation" type="number" min="0" step="0.1" required/></label><label>Review<input name="review" type="number" min="0" step="0.1" required/></label><label>Editing<input name="edit" type="number" min="0" step="0.1" required/></label></div><div className="formula-strip"><b>EchoFlow total</b><span>generation + review + editing</span></div><button className="primary wide-button">Calculate and save</button></form><article className="panel benchmark-table"><div className="panel-title"><div><span>RECENT RECORDS</span><h2>Evaluation log</h2></div></div><div className="mini-table">{workspace.benchmarks.slice(0, 12).map((item) => <div key={item.benchmark_id}><span><strong>{workspace.solutions.find((solution) => solution.solution_id === item.solution_id)?.solution_name}</strong><small>{item.content_type} · {item.benchmark_id}</small></span><span><small>Manual</small><b>{item.manual_minutes}m</b></span><span><small>EchoFlow</small><b>{item.total_ai_minutes}m</b></span><span className={item.time_reduction_percentage >= 0 ? "saved" : "lost"}><small>Reduction</small><b>{percent(item.time_reduction_percentage)}</b></span></div>)}</div></article></section></>;
}

function SettingsView({ workspace, update, persistence }: { workspace: Workspace; update: (fn: (value: Workspace) => Workspace, message: string) => void; persistence: string }) {
  function reset() { if (!window.confirm("Reset the workspace to the reproducible fictional evaluation dataset?")) return; update(() => buildDemoWorkspace(), "Demo evaluation workspace restored."); }
  function exportAll() { const files = exportFiles(workspace); Object.entries(files).forEach(([name, body], index) => setTimeout(() => download(name, body), index * 120)); download("echoflow_workspace.json", JSON.stringify(workspace, null, 2), "application/json"); }
  return <><PageHeader eyebrow="Workspace configuration" title="Settings & data provenance" description="Control generation mode, export traceable records and understand what this prototype does—and does not—claim."/><section className="settings-grid"><article className="panel"><div className="panel-title"><div><span>GENERATION</span><h2>Model mode</h2></div><span className={`connection-badge ${workspace.settings.generation_mode}`}>{workspace.settings.generation_mode.toUpperCase()}</span></div><label className="radio-card"><input type="radio" checked={workspace.settings.generation_mode === "demo"} onChange={() => update((value) => ({ ...value, settings: { ...value.settings, generation_mode: "demo" } }), "Demo Mode enabled.")}/><span><strong>Demo Mode</strong><small>Always available. Deterministic, evidence-conscious output from supplied records.</small></span></label><label className="radio-card"><input type="radio" checked={workspace.settings.generation_mode === "api"} onChange={() => update((value) => ({ ...value, settings: { ...value.settings, generation_mode: "api" } }), "API mode selected; missing keys fall back safely.")}/><span><strong>API Mode</strong><small>Uses a server-side key when configured; automatically falls back to Demo Mode.</small></span></label><div className="setting-row"><span><strong>Persistence</strong><small>{persistence}</small></span><i className={persistence.startsWith("Cloud") ? "ok" : "neutral"}/></div></article><article className="panel"><div className="panel-title"><div><span>EXPORT</span><h2>Evidence package</h2></div></div><p className="setting-copy">Download solutions, content assets, review events, workflow benchmarks, analytics summary and the complete JSON workspace.</p><button className="primary wide-button" onClick={exportAll}>Export all records</button><div className="file-list">{Object.keys(exportFiles(workspace)).map((name) => <button key={name} onClick={() => download(name, exportFiles(workspace)[name as keyof ReturnType<typeof exportFiles>])}><span>CSV</span>{name}<b>↓</b></button>)}</div></article><article className="panel span-two"><div className="panel-title"><div><span>DATA PROVENANCE</span><h2>Prototype boundaries</h2></div></div><div className="boundary-grid"><div><b>Included</b><p>Fictional smart-city solution records, stakeholder profiles, generated evaluation assets, review events, reuse records and complete-workflow benchmark observations.</p></div><div><b>Not claimed</b><p>No Digital Zhengzhou internal product data, real clients, government partnerships, CRM integration, automated publishing, government database connection or procurement-system integration.</p></div><div><b>Future pathway</b><p>Approved product catalogues, enterprise identity, CRM references and publishing connectors can be integrated after data governance and security review.</p></div></div><button className="danger-outline" onClick={reset}>Reset reproducible demo dataset</button></article></section></>;
}

export default function Home() {
  const [page, setPage] = useState<Page>("Dashboard"); const [workspace, setWorkspace] = useState<Workspace>(() => buildDemoWorkspace()); const [toast, setToast] = useState(""); const [persistence, setPersistence] = useState("Checking cloud workspace…"); const analytics = useMemo(() => calculateAnalytics(workspace), [workspace]);
  useEffect(() => { let cancelled = false; fetch("/api/state?key=solution-marketing-workspace").then(async (response) => { if (!response.ok) throw new Error(); const payload = await response.json() as { value: unknown }; if (!cancelled && isWorkspace(payload.value)) setWorkspace(payload.value); if (!cancelled) setPersistence("Cloud D1 workspace connected"); }).catch(() => { if (!cancelled) setPersistence("Demo session active; cloud binding unavailable locally"); }); return () => { cancelled = true; }; }, []);
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2800); }
  function update(fn: (value: Workspace) => Workspace, message: string) { setWorkspace((current) => { const next = fn(current); fetch("/api/state", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ key: "solution-marketing-workspace", value: next }) }).then((response) => { if (response.ok) setPersistence("Cloud D1 workspace connected"); }).catch(() => setPersistence("Demo session active; cloud binding unavailable locally")); return next; }); notify(message); }
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">E</div><div><strong>EchoFlow</strong><span>Solution Marketing Studio</span></div></div><nav aria-label="Primary navigation"><span className="nav-label">WORKSPACE</span>{navItems.map((item) => <button key={item.page} className={page === item.page ? "active" : ""} onClick={() => setPage(item.page)}><i>{item.icon}</i><span>{item.page}</span>{item.page === "Review" && <b>{workspace.assets.filter((asset) => asset.review_status === "in_review").length}</b>}</button>)}</nav><div className="sidebar-foot"><div className="mode-card"><span>GENERATION MODE</span><strong><i/> {workspace.settings.generation_mode === "demo" ? "Demo Mode" : "API + fallback"}</strong><small>No key is required to run.</small></div><div className="company"><div>DZ</div><span><strong>Digital Zhengzhou</strong><small>Marketing Technology Prototype</small></span></div></div></aside><main><div className="topbar"><div><span className="crumb">EchoFlow / {page}</span><span className="sync"><i/> {persistence}</span></div><div className="top-actions"><button onClick={() => setPage("Analytics")}>Evaluation: {workspace.assets.length} assets</button><span className="user">EZ</span></div></div><div className="page-content">{page === "Dashboard" && <Dashboard workspace={workspace} analytics={analytics} setPage={setPage}/>} {page === "Solutions" && <SolutionsView workspace={workspace} update={update}/>} {page === "Generate" && <GenerateView workspace={workspace} update={update} setPage={setPage}/>} {page === "Content Library" && <LibraryView workspace={workspace}/>} {page === "Review" && <ReviewView workspace={workspace} update={update}/>} {page === "Analytics" && <AnalyticsView workspace={workspace} analytics={analytics}/>} {page === "Benchmark" && <BenchmarkView workspace={workspace} analytics={analytics} update={update}/>} {page === "Settings" && <SettingsView workspace={workspace} update={update} persistence={persistence}/>}</div></main>{toast && <div className="toast"><span>✓</span>{toast}</div>}</div>;
}
