

"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import {
  Analytics,
  CONTENT_TYPES,
  ContentAsset,
  exportFiles,
  groupCount,
  isWorkspace,
  MARKETING_OBJECTIVES,
  makeBenchmark,
  MessagingStrategy,
  REUSE_CONTEXTS,
  ReviewStatus,
  Solution,
  Workspace,
  applyContentEdit,
  applyReuse,
  applyReviewDecision,
  buildDemoWorkspace,
  calculateAnalytics,
  createStrategy,
  generateDemoCopy,
} from "./lib/echoflow";

type Page = "Dashboard" | "Solutions" | "Generate" | "Content Library" | "Review" | "Analytics" | "Benchmark" | "Settings";

const PAGE_LABELS: Record<Page, string> = { Dashboard: "仪表盘", Solutions: "解决方案", Generate: "内容生成", "Content Library": "内容资产库", Review: "人工审核", Analytics: "数据分析", Benchmark: "效率评测", Settings: "设置" };

const navItems: { page: Page; icon: string }[] = [
  { page: "Dashboard", icon: "◫" }, { page: "Solutions", icon: "◇" }, { page: "Generate", icon: "✦" },
  { page: "Content Library", icon: "▤" }, { page: "Review", icon: "✓" }, { page: "Analytics", icon: "↗" },
  { page: "Benchmark", icon: "◷" }, { page: "Settings", icon: "⚙" },
];

const statusLabels: Record<ReviewStatus, string> = { draft: "草稿", in_review: "审核中", approved: "已批准", rejected: "已驳回", final: "已定稿" };

function percent(value: number) { return `${value.toFixed(1)}%`; }
function minutes(value: number) { return `${value.toFixed(1)} 分钟`; }
function download(name: string, body: string, type = "text/csv;charset=utf-8") {
  const url = URL.createObjectURL(new Blob(["\ufeff", body], { type }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url);
}

function KpiCard({ label, value, note, accent = "indigo" }: { label: string; value: string | number; note: string; accent?: string }) {
  return <article className={`kpi-card ${accent}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>;
}

function PageHeader({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: React.ReactNode }) {
  return <header className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{actions && <div className="heading-actions">{actions}</div>}</header>;
}

function MetricBar({ label, value, max, suffix = "" }: { label: string; value: number; max: number; suffix?: string }) {
  return <div className="metric-row"><div><span>{label}</span><strong>{value}{suffix}</strong></div><div className="metric-track"><i style={{ width: `${Math.max(3, (value / Math.max(max, 1)) * 100)}%` }} /></div></div>;
}

function Dashboard({ workspace, analytics, setPage }: { workspace: Workspace; analytics: Analytics; setPage: (page: Page) => void }) {
  const bySolution = groupCount(workspace.assets, (asset) => workspace.solutions.find((solution) => solution.solution_id === asset.solution_id)?.solution_name ?? asset.solution_id).slice(0, 5);


  const byStakeholder = groupCount(workspace.assets, (asset) => workspace.stakeholders.find((stakeholder) => stakeholder.stakeholder_id === asset.stakeholder_id)?.name ?? asset.stakeholder_id);
  return <>
    <section className="hero-panel">
      <div className="hero-copy"><span className="hero-kicker">AI 辅助解决方案营销运营</span><h1>让复杂方案变成面向关键角色的专业内容。</h1><p>EchoFlow 帮助营销团队将智慧城市与数字政务方案信息，转化为有依据、面向不同关键角色的营销与销售支持内容。</p><div className="hero-actions"><button className="primary" onClick={() => setPage("Generate")}>生成内容 <b>→</b></button><button className="secondary" onClick={() => setPage("Solutions")}>浏览解决方案</button></div></div>
      <div className="workflow-card"><span>标准化工作流</span>{["解决方案", "关键角色", "信息策略", "AI 初稿", "人工审核", "内容复用"].map((item, index) => <div key={item}><b>{String(index + 1).padStart(2, "0")}</b><strong>{item}</strong>{index < 5 && <i>↓</i>}</div>)}</div>
    </section>
    <section className="kpi-grid four"><KpiCard label="管理中的解决方案" value={analytics.solution_count} note="虚构演示方案记录"/><KpiCard label="关键角色细分" value={analytics.stakeholder_count} note="可复用角色画像" accent="blue"/><KpiCard label="内容资产" value={analytics.content_asset_count} note="工作区生成记录" accent="teal"/><KpiCard label="首次审核通过率" value={percent(analytics.first_pass_approval_rate)} note={`${analytics.reviewed_asset_count} 条已审核资产`} accent="amber"/></section>
    <section className="two-columns">
      <article className="panel efficiency-panel"><div className="panel-title"><div><span>效率表现</span><h2>内容适配工作流</h2></div><button className="text-button" onClick={() => setPage("Benchmark")}>查看评测 →</button></div><div className="comparison"><div><span>人工平均耗时</span><strong>{minutes(analytics.manual_adaptation_time)}</strong><i className="manual-line" /></div><div><span>EchoFlow 平均耗时</span><strong>{minutes(analytics.ai_adaptation_time)}</strong><i className="ai-line" style={{ width: `${Math.min(100, (analytics.ai_adaptation_time / Math.max(analytics.manual_adaptation_time, 1)) * 100)}%` }} /></div></div><div className="saving-callout"><b>{percent(analytics.time_reduction_rate)}</b><span>平均时间节省<br/><small>包含生成、审核与编辑全流程。</small></span></div></article>
      <article className="panel"><div className="panel-title"><div><span>内容表现</span><h2>人工审核结果</h2></div><button className="text-button" onClick={() => setPage("Analytics")}>查看数据分析 →</button></div><div className="performance-grid"><div><strong>{percent(analytics.first_pass_approval_rate)}</strong><span>首次审核通过率</span></div><div><strong>{percent(analytics.content_reuse_rate)}</strong><span>已批准资产复用率</span></div><div><strong>{analytics.average_edit_count}</strong><span>平均编辑次数</span></div><div><strong>{minutes(analytics.average_review_time_minutes)}</strong><span>平均审核耗时</span></div></div></article>
    </section>
    <section className="two-columns">
      <article className="panel"><div className="panel-title"><div><span>方案组合</span><h2>按解决方案统计资产</h2></div></div><div className="metric-list">{bySolution.map((item) => <MetricBar key={item.label} {...item} max={Math.max(...bySolution.map((entry) => entry.value))}/>)}</div></article>
      <article className="panel"><div className="panel-title"><div><span>角色细分</span><h2>按关键角色统计资产</h2></div></div><div className="metric-list">{byStakeholder.map((item) => <MetricBar key={item.label} {...item} max={Math.max(...byStakeholder.map((entry) => entry.value))}/>)}</div></article>
    </section>
  </>;
}

function SolutionsView({ workspace, update }: { workspace: Workspace; update: (fn: (value: Workspace) => Workspace, message: string) => void }) {
  const [query, setQuery] = useState(""); const [showForm, setShowForm] = useState(false); const [selected, setSelected] = useState(workspace.solutions[0]?.solution_id ?? "");
  const filtered = workspace.solutions.filter((solution) => `${solution.solution_name} ${solution.solution_category} ${solution.short_description}`.toLowerCase().includes(query.toLowerCase()));
  const active = workspace.solutions.find((solution) => solution.solution_id === selected) ?? filtered[0];
  function createSolutionRecord(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const now = new Date().toISOString();
    const record: Solution = { solution_id: `SOL-${Date.now()}`, solution_name: String(data.get("name") ?? "").trim(), solution_category: String(data.get("category") ?? "").trim(), short_description: String(data.get("description") ?? "").trim(), business_problem: String(data.get("problem") ?? "").trim(), key_capabilities: String(data.get("capabilities") ?? "").split("\n").filter(Boolean), target_users: String(data.get("users") ?? "").split("\n").filter(Boolean), business_value: String(data.get("value") ?? "").split("\n").filter(Boolean), technical_highlights: String(data.get("technical") ?? "").split("\n").filter(Boolean), implementation_context: String(data.get("context") ?? "").trim(), source_reference: String(data.get("source") ?? "").trim() || "用户提供的工作区记录", created_at: now, updated_at: now };
    if (!record.solution_name || !record.solution_category || !record.short_description || !record.business_problem || !record.key_capabilities.length) return;
    update((value) => ({ ...value, solutions: [record, ...value.solutions] }), "解决方案已加入方案库。"); setShowForm(false); setSelected(record.solution_id); event.currentTarget.reset();
  }
  return <><PageHeader eyebrow="解决方案管理" title="解决方案库" description="建立一次有依据的方案源记录，再针对不同关键角色调整价值表达。" actions={<><label className="search"><span>⌕</span><input aria-label="搜索解决方案" placeholder="搜索解决方案" value={query} onChange={(event) => setQuery(event.target.value)}/></label><button className="primary" onClick={() => setShowForm(true)}>+ 添加解决方案</button></>}/>
    <div className="library-layout"><aside className="solution-list"><div className="list-caption"><span>{filtered.length} 个解决方案</span><small>演示数据均已明确标注</small></div>{filtered.map((solution) => <button key={solution.solution_id} className={active?.solution_id === solution.solution_id ? "active" : ""} onClick={() => setSelected(solution.solution_id)}><i>{solution.solution_category.slice(0, 2).toUpperCase()}</i><span><strong>{solution.solution_name}</strong><small>{solution.solution_category}</small></span><b>›</b></button>)}</aside>
      {active && <article className="solution-detail"><div className="detail-header"><div><span className="category-pill">{active.solution_category}</span><h2>{active.solution_name}</h2><p>{active.short_description}</p></div><span className="demo-badge">虚构演示</span></div><div className="detail-grid"><section><span>业务问题</span><p>{active.business_problem}</p></section><section><span>实施场景</span><p>{active.implementation_context}</p></section><section><span>核心能力</span><ul>{active.key_capabilities.map((item) => <li key={item}>{item}</li>)}</ul></section><section><span>业务价值</span><ul>{active.business_value.map((item) => <li key={item}>{item}</li>)}</ul></section><section><span>技术亮点</span><ul>{active.technical_highlights.map((item) => <li key={item}>{item}</li>)}</ul></section><section><span>目标用户</span><ul>{active.target_users.map((item) => <li key={item}>{item}</li>)}</ul></section></div><footer><span>来源依据</span><p>{active.source_reference}</p></footer></article>}</div>
    {showForm && <div className="modal-backdrop" onMouseDown={() => setShowForm(false)}><form className="modal solution-form" onSubmit={createSolutionRecord} onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><span>新建方案源记录</span><h2>添加解决方案</h2></div><button type="button" onClick={() => setShowForm(false)}>×</button></div><div className="form-grid"><label>方案名称<input name="name" required/></label><label>方案类别<input name="category" required/></label><label className="wide">简要说明<textarea name="description" required/></label><label className="wide">业务问题<textarea name="problem" required/></label><label>核心能力 <small>每行一项</small><textarea name="capabilities" required/></label><label>业务价值 <small>每行一项</small><textarea name="value" required/></label><label>目标用户<textarea name="users"/></label><label>技术亮点<textarea name="technical"/></label><label className="wide">实施场景<textarea name="context"/></label><label className="wide">来源依据<input name="source" placeholder="文档、访谈或用户提供的来源"/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={() => setShowForm(false)}>取消</button><button className="primary">保存方案</button></div></form></div>}
  </>;
}

function GenerateView({ workspace, update, setPage }: { workspace: Workspace; update: (fn: (value: Workspace) => Workspace, message: string) => void; setPage: (page: Page) => void }) {
  const [solutionId, setSolutionId] = useState(workspace.solutions[0]?.solution_id ?? ""); const [stakeholderId, setStakeholderId] = useState(workspace.stakeholders[0]?.stakeholder_id ?? ""); const [objective, setObjective] = useState<string>(MARKETING_OBJECTIVES[0]); const [contentType, setContentType] = useState<string>(CONTENT_TYPES[0]); const [strategy, setStrategy] = useState<MessagingStrategy | null>(() => workspace.solutions[0] && workspace.stakeholders[0] ? createStrategy(workspace.solutions[0], workspace.stakeholders[0], MARKETING_OBJECTIVES[0], CONTENT_TYPES[0]) : null); const [busy, setBusy] = useState(false);
  const solution = workspace.solutions.find((item) => item.solution_id === solutionId); const stakeholder = workspace.stakeholders.find((item) => item.stakeholder_id === stakeholderId);
  useEffect(() => { const next = solution && stakeholder ? createStrategy(solution, stakeholder, objective, contentType) : null; queueMicrotask(() => setStrategy(next)); }, [solution, stakeholder, objective, contentType]);
  function editStrategy(field: keyof MessagingStrategy, value: string) { setStrategy((current) => current ? { ...current, [field]: value } : current); }
  async function generate() {
    if (!solution || !stakeholder || !strategy || !strategy.core_value_proposition.trim()) return; setBusy(true); const started = performance.now(); let result = generateDemoCopy(solution, stakeholder, strategy); let mode: "demo" | "api" = "demo";
    try { const response = await fetch("/api/generate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ solution, stakeholder, strategy, requestedMode: workspace.settings.generation_mode }) }); if (response.ok) { const payload = await response.json() as { title: string; content: string; mode: "demo" | "api" }; result = { title: payload.title, content: payload.content }; mode = payload.mode; } } catch { /* deterministic fallback remains available */ }
    const now = new Date().toISOString(); const id = `AST-${Date.now()}`; const asset: ContentAsset = { draft_id: id, solution_id: solution.solution_id, stakeholder_id: stakeholder.stakeholder_id, content_type: contentType, marketing_objective: objective, title: result.title, content: result.content, generated_at: now, generation_seconds: Number(Math.max((performance.now() - started) / 1000, 0.1).toFixed(1)), generation_mode: mode, review_status: "in_review", approved_first_pass: null, edit_count: 0, review_time_minutes: 0, finalised_at: null, reuse_count: 0, reuse_context: [], version: 1 };
    update((value) => ({ ...value, strategies: [strategy, ...value.strategies], assets: [asset, ...value.assets], reviews: [{ review_id: `REV-${Date.now()}`, draft_id: id, action: "submitted", occurred_at: now, duration_minutes: 0, note: "已提交人工审核。" }, ...value.reviews] }), `${mode === "api" ? "API 模式" : "演示模式"}初稿已生成并进入审核。`); setBusy(false); setPage("Review");
  }
  return <><PageHeader eyebrow="引导式生成" title="生成面向不同关键角色的内容" description="先搭建并审核信息策略，再生成受事实约束的内容初稿。"/><div className="generate-layout"><section className="panel generator-controls"><div className="step-heading"><b>01</b><div><h2>设置内容简报</h2><p>四项输入共同定义内容场景。</p></div></div><label>解决方案<select value={solutionId} onChange={(event) => setSolutionId(event.target.value)}>{workspace.solutions.map((item) => <option key={item.solution_id} value={item.solution_id}>{item.solution_name}</option>)}</select></label><label>关键角色<select value={stakeholderId} onChange={(event) => setStakeholderId(event.target.value)}>{workspace.stakeholders.map((item) => <option key={item.stakeholder_id} value={item.stakeholder_id}>{item.name}</option>)}</select></label><label>营销目标<select value={objective} onChange={(event) => setObjective(event.target.value)}>{MARKETING_OBJECTIVES.map((item) => <option key={item}>{item}</option>)}</select></label><label>内容类型<select value={contentType} onChange={(event) => setContentType(event.target.value)}>{CONTENT_TYPES.map((item) => <option key={item}>{item}</option>)}</select></label>{stakeholder && <div className="stakeholder-card"><span>{stakeholder.technical_depth} 技术深度</span><strong>{stakeholder.name}</strong><p>优先突出：{stakeholder.messaging_priority.join("、")}。</p><small>风险重点：{stakeholder.risk_concerns.join(" · ")}</small></div>}</section>
      <section className="panel strategy-editor"><div className="step-heading"><b>02</b><div><h2>审核信息策略</h2><p>正式生成前可编辑全部字段。</p></div><span className="editable-badge">可编辑</span></div>{strategy && <div className="strategy-fields"><label>核心价值主张<textarea value={strategy.core_value_proposition} onChange={(event) => editStrategy("core_value_proposition", event.target.value)}/></label><label>三条关键信息<textarea value={strategy.key_messages.join("\n")} onChange={(event) => setStrategy({ ...strategy, key_messages: event.target.value.split("\n").filter(Boolean) })}/></label><label>支持依据<textarea value={strategy.supporting_proof_points.join("\n")} onChange={(event) => setStrategy({ ...strategy, supporting_proof_points: event.target.value.split("\n").filter(Boolean) })}/></label><div className="field-pair"><label>建议语气<input value={strategy.recommended_tone} onChange={(event) => editStrategy("recommended_tone", event.target.value)}/></label><label>CTA<input value={strategy.cta} onChange={(event) => editStrategy("cta", event.target.value)}/></label></div><label>内容切入角度<input value={strategy.content_angle} onChange={(event) => editStrategy("content_angle", event.target.value)}/></label></div>}<div className="guardrail-box"><b>✓ 事实约束已启用</b><p>不得虚构数据、合作关系、客户案例或技术能力；生成的营销表达与已提供事实明确区分。</p></div><button className="generate-cta" disabled={busy || !strategy?.core_value_proposition.trim()} onClick={generate}><span>✦</span><div><strong>{busy ? "正在生成基于事实的初稿…" : "生成内容初稿"}</strong><small>{workspace.settings.generation_mode === "demo" ? "确定性演示模式——无需 API Key" : "API 模式，异常时自动回退演示模式"}</small></div><b>→</b></button></section></div></>;
}

function AssetTable({ workspace, assets, actions }: { workspace: Workspace; assets: ContentAsset[]; actions?: (asset: ContentAsset) => React.ReactNode }) {
  return <div className="table-wrap"><table><thead><tr><th>内容资产</th><th>解决方案 / 关键角色</th><th>类型</th><th>状态</th><th>编辑次数</th><th>复用次数</th>{actions && <th>操作</th>}</tr></thead><tbody>{assets.map((asset) => { const solution = workspace.solutions.find((item) => item.solution_id === asset.solution_id); const stakeholder = workspace.stakeholders.find((item) => item.stakeholder_id === asset.stakeholder_id); return <tr key={asset.draft_id}><td><strong>{asset.title}</strong><small>{asset.draft_id} · V{asset.version} · {asset.generation_mode === "demo" ? "演示模式" : "API 模式"}</small></td><td><span>{solution?.solution_name}</span><small>{stakeholder?.name}</small></td><td>{asset.content_type}</td><td><span className={`status ${asset.review_status}`}>{statusLabels[asset.review_status]}</span></td><td>{asset.edit_count}</td><td>{asset.reuse_count}</td>{actions && <td><div className="row-actions">{actions(asset)}</div></td>}</tr>; })}</tbody></table>{!assets.length && <div className="empty"><b>没有符合条件的内容资产</b><span>请调整筛选条件或生成新的初稿。</span></div>}</div>;
}

function LibraryView({ workspace }: { workspace: Workspace }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all");
  const assets = workspace.assets.filter((asset) => (status === "all" || asset.review_status === status) && `${asset.title} ${asset.content_type}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader eyebrow="内容运营" title="内容资产库" description="检索所有生成资产，并查看审核结果、编辑历史和复用记录。" actions={<button className="primary" onClick={() => download("content_assets.csv", exportFiles(workspace)["content_assets.csv"])}>导出资产</button>}/><div className="filter-bar"><label className="search grow"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索标题或内容类型"/></label><select aria-label="按状态筛选" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">全部状态</option>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><span className="record-count">{assets.length} 条记录</span></div><AssetTable workspace={workspace} assets={assets}/></>;
}

function ReviewView({ workspace, update }: { workspace: Workspace; update: (fn: (value: Workspace) => Workspace, message: string) => void }) {
  const [filter, setFilter] = useState<ReviewStatus | "all">("in_review"); const [editing, setEditing] = useState<ContentAsset | null>(null); const [reuseContext, setReuseContext] = useState<string>(REUSE_CONTEXTS[0]);
  const assets = workspace.assets.filter((asset) => filter === "all" || asset.review_status === filter).slice(0, 40);
  function transition(asset: ContentAsset, status: ReviewStatus, action: "approved" | "rejected" | "finalised") { update((value) => applyReviewDecision(value, asset.draft_id, action), `内容已标记为${statusLabels[status]}。`); }
  function saveEdit() { if (!editing || !editing.title.trim() || !editing.content.trim()) return; update((value) => applyContentEdit(value, editing.draft_id, editing.title, editing.content), "编辑已保存，审核历史已更新。"); setEditing(null); }
  function regenerate(asset: ContentAsset) { const solution = workspace.solutions.find((item) => item.solution_id === asset.solution_id); const stakeholder = workspace.stakeholders.find((item) => item.stakeholder_id === asset.stakeholder_id); if (!solution || !stakeholder) return; const strategy = workspace.strategies.find((item) => item.solution_id === asset.solution_id && item.stakeholder_id === asset.stakeholder_id) ?? createStrategy(solution, stakeholder, asset.marketing_objective, asset.content_type); const copy = generateDemoCopy(solution, stakeholder, strategy); const now = new Date().toISOString(); update((value) => ({ ...value, assets: value.assets.map((item) => item.draft_id === asset.draft_id ? { ...item, ...copy, version: item.version + 1, edit_count: item.edit_count + 1, review_status: "in_review", approved_first_pass: item.approved_first_pass ?? false, generated_at: now } : item), reviews: [{ review_id: `REV-${Date.now()}`, draft_id: asset.draft_id, action: "regenerated", occurred_at: now, duration_minutes: 0, note: "已在确定性演示模式下重新生成。" }, ...value.reviews] }), "已生成新的演示版本。"); }


  function markReuse(asset: ContentAsset) { update((value) => applyReuse(value, asset.draft_id, reuseContext), `已记录复用场景：${reuseContext}。`); }
  return <><PageHeader eyebrow="人工闭环" title="审核队列" description="支持批准、驳回、编辑、重新生成和定稿；每次操作都会更新可追溯的流程记录。" actions={<div className="reuse-control"><select value={reuseContext} onChange={(event) => setReuseContext(event.target.value)}>{REUSE_CONTEXTS.map((item) => <option key={item}>{item}</option>)}</select><small>复用场景</small></div>}/><div className="status-tabs">{(["all", "in_review", "approved", "rejected", "final"] as const).map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item === "all" ? "全部" : statusLabels[item]} <b>{item === "all" ? workspace.assets.length : workspace.assets.filter((asset) => asset.review_status === item).length}</b></button>)}</div><AssetTable workspace={workspace} assets={assets} actions={(asset) => <>{asset.review_status === "in_review" && <><button className="small positive" onClick={() => transition(asset, "approved", "approved")}>批准</button><button className="small danger" onClick={() => transition(asset, "rejected", "rejected")}>驳回</button></>}<button className="small" onClick={() => setEditing(asset)}>编辑</button><button className="small" onClick={() => regenerate(asset)}>重新生成</button>{asset.review_status === "approved" && <button className="small positive" onClick={() => transition(asset, "final", "finalised")}>定稿</button>}{(asset.review_status === "approved" || asset.review_status === "final") && <button className="small reuse" onClick={() => markReuse(asset)}>标记复用</button>}</>}/>
    {editing && <div className="modal-backdrop" onMouseDown={() => setEditing(null)}><section className="modal editor" onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><span>人工审核 · {editing.draft_id}</span><h2>编辑内容</h2></div><button onClick={() => setEditing(null)}>×</button></div><label>标题<input value={editing.title} onChange={(event) => setEditing({ ...editing, title: event.target.value })}/></label><label>正文<textarea value={editing.content} onChange={(event) => setEditing({ ...editing, content: event.target.value })}/></label><div className="evidence-note">编辑会创建新版本，该资产将不再计入首次审核通过。</div><div className="modal-actions"><button className="secondary" onClick={() => setEditing(null)}>取消</button><button className="primary" onClick={saveEdit}>保存为 V{editing.version + 1}</button></div></section></div>}
  </>;
}

function AnalyticsView({ workspace, analytics }: { workspace: Workspace; analytics: Analytics }) {
  const contentTypes = groupCount(workspace.assets, (asset) => asset.content_type); const stakeholders = groupCount(workspace.assets, (asset) => workspace.stakeholders.find((item) => item.stakeholder_id === asset.stakeholder_id)?.name ?? asset.stakeholder_id); const maxType = Math.max(...contentTypes.map((item) => item.value));
  return <><PageHeader eyebrow="数据可追溯" title="数据分析" description="以下所有数字均根据工作区中的内容、审核、复用和效率评测记录实时重算。" actions={<button className="primary" onClick={() => download("analytics_summary.csv", exportFiles(workspace)["analytics_summary.csv"])}>导出汇总</button>}/><div className="provenance-banner"><span>✓</span><div><strong>实时计算</strong><p>所有结果均由记录实时计算。当前样本：{workspace.assets.length} 条资产、{analytics.reviewed_asset_count} 条审核记录和 {workspace.benchmarks.length} 条完整工作流评测记录。</p></div></div><section className="kpi-grid four"><KpiCard label="已批准资产" value={analytics.approved_asset_count} note="已批准 + 已定稿记录"/><KpiCard label="首次审核通过率" value={percent(analytics.first_pass_approval_rate)} note="首次通过 ÷ 已审核资产" accent="blue"/><KpiCard label="内容复用率" value={percent(analytics.content_reuse_rate)} note="已批准且复用 ÷ 已批准资产" accent="teal"/><KpiCard label="平均编辑次数" value={analytics.average_edit_count} note="编辑总次数 ÷ 全部资产" accent="amber"/></section><section className="kpi-grid four"><KpiCard label="平均生成耗时" value={`${analytics.average_generation_time_seconds} 秒`} note="生成耗时记录均值"/><KpiCard label="平均审核耗时" value={minutes(analytics.average_review_time_minutes)} note="已审核资产耗时均值" accent="blue"/><KpiCard label="人工适配耗时" value={minutes(analytics.manual_adaptation_time)} note="人工基准均值" accent="teal"/><KpiCard label="平均节时率" value={percent(analytics.time_reduction_rate)} note="逐条节时率均值" accent="amber"/></section><section className="two-columns"><article className="panel"><div className="panel-title"><div><span>分类明细</span><h2>按内容类型统计资产</h2></div></div><div className="metric-list dense">{contentTypes.map((item) => <MetricBar key={item.label} {...item} max={maxType}/>)}</div></article><article className="panel"><div className="panel-title"><div><span>分类明细</span><h2>按关键角色统计资产</h2></div></div><div className="segment-list">{stakeholders.map((item) => <div key={item.label}><span><i>{item.label.slice(0, 2).toUpperCase()}</i><strong>{item.label}</strong></span><b>{item.value}</b></div>)}</div><div className="formula-box"><span>核心公式</span><code>首次通过率 = 首次通过资产 / 已审核资产</code><code>复用率 = 至少复用一次的已批准资产 / 已批准资产</code><code>AI 辅助耗时 = 生成 + 审核 + 编辑</code></div></article></section></>;
}

function BenchmarkView({ workspace, analytics, update }: { workspace: Workspace; analytics: Analytics; update: (fn: (value: Workspace) => Workspace, message: string) => void }) {
  const [solutionId, setSolutionId] = useState(workspace.solutions[0]?.solution_id ?? ""); const [stakeholderId, setStakeholderId] = useState(workspace.stakeholders[0]?.stakeholder_id ?? ""); const [contentType, setContentType] = useState<string>(CONTENT_TYPES[0]);
  function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const numbers = ["manual", "generation", "review", "edit"].map((key) => Number(data.get(key))); if (numbers.some((value) => !Number.isFinite(value) || value < 0) || numbers[0] <= 0) return; const record = makeBenchmark({ benchmark_id: `BM-${Date.now()}`, solution_id: solutionId, stakeholder_id: stakeholderId, content_type: contentType, manual_minutes: numbers[0], ai_generation_minutes: numbers[1], ai_review_minutes: numbers[2], ai_edit_minutes: numbers[3], timestamp: new Date().toISOString() }); update((value) => ({ ...value, benchmarks: [record, ...value.benchmarks] }), `评测已保存：${record.time_reduction_percentage}% 时间节省。`); event.currentTarget.reset(); }
  return <><PageHeader eyebrow="工作流测量" title="人工与 EchoFlow 效率评测" description="比较完整工作流，而不仅是模型生成速度；审核和编辑耗时始终计入。" actions={<button className="primary" onClick={() => download("benchmarks.csv", exportFiles(workspace)["benchmarks.csv"])}>导出评测</button>}/><section className="kpi-grid three"><KpiCard label="平均人工耗时" value={minutes(analytics.manual_adaptation_time)} note={`${workspace.benchmarks.length} 条评测记录`}/><KpiCard label="EchoFlow 平均耗时" value={minutes(analytics.ai_adaptation_time)} note="生成 + 审核 + 编辑" accent="blue"/><KpiCard label="平均节时率" value={percent(analytics.time_reduction_rate)} note="逐条节时率均值" accent="teal"/></section><section className="benchmark-layout"><form className="panel benchmark-form" onSubmit={add}><div className="panel-title"><div><span>新增观察记录</span><h2>记录一次效率评测</h2></div></div><label>解决方案<select value={solutionId} onChange={(event) => setSolutionId(event.target.value)}>{workspace.solutions.map((item) => <option key={item.solution_id} value={item.solution_id}>{item.solution_name}</option>)}</select></label><label>关键角色<select value={stakeholderId} onChange={(event) => setStakeholderId(event.target.value)}>{workspace.stakeholders.map((item) => <option key={item.stakeholder_id} value={item.stakeholder_id}>{item.name}</option>)}</select></label><label>内容类型<select value={contentType} onChange={(event) => setContentType(event.target.value)}>{CONTENT_TYPES.map((item) => <option key={item}>{item}</option>)}</select></label><div className="time-inputs"><label>人工耗时（分钟）<input name="manual" type="number" min="0.1" step="0.1" required/></label><label>生成耗时<input name="generation" type="number" min="0" step="0.1" required/></label><label>审核耗时<input name="review" type="number" min="0" step="0.1" required/></label><label>编辑耗时<input name="edit" type="number" min="0" step="0.1" required/></label></div><div className="formula-strip"><b>EchoFlow 总耗时</b><span>生成 + 审核 + 编辑</span></div><button className="primary wide-button">计算并保存</button></form><article className="panel benchmark-table"><div className="panel-title"><div><span>近期记录</span><h2>评测日志</h2></div></div><div className="mini-table">{workspace.benchmarks.slice(0, 12).map((item) => <div key={item.benchmark_id}><span><strong>{workspace.solutions.find((solution) => solution.solution_id === item.solution_id)?.solution_name}</strong><small>{item.content_type} · {item.benchmark_id}</small></span><span><small>人工</small><b>{item.manual_minutes} 分钟</b></span><span><small>EchoFlow</small><b>{item.total_ai_minutes} 分钟</b></span><span className={item.time_reduction_percentage >= 0 ? "saved" : "lost"}><small>节省比例</small><b>{percent(item.time_reduction_percentage)}</b></span></div>)}</div></article></section></>;
}

function SettingsView({ workspace, update, persistence }: { workspace: Workspace; update: (fn: (value: Workspace) => Workspace, message: string) => void; persistence: string }) {
  function reset() { if (!window.confirm("确定将工作区重置为可复现的虚构评估数据集吗？")) return; update(() => buildDemoWorkspace(), "演示评估工作区已恢复。"); }
  function exportAll() { const files = exportFiles(workspace); Object.entries(files).forEach(([name, body], index) => setTimeout(() => download(name, body), index * 120)); download("echoflow_workspace.json", JSON.stringify(workspace, null, 2), "application/json"); }
  return <><PageHeader eyebrow="工作区配置" title="设置与数据来源" description="管理生成模式、导出可追溯记录，并明确本原型已实现与未实现的边界。"/><section className="settings-grid"><article className="panel"><div className="panel-title"><div><span>内容生成</span><h2>模型模式</h2></div><span className={`connection-badge ${workspace.settings.generation_mode}`}>{workspace.settings.generation_mode === "demo" ? "演示模式" : "API 模式"}</span></div><label className="radio-card"><input type="radio" checked={workspace.settings.generation_mode === "demo"} onChange={() => update((value) => ({ ...value, settings: { ...value.settings, generation_mode: "demo" } }), "已启用演示模式。")}/><span><strong>演示模式</strong><small>始终可用。仅根据已提供记录生成确定性、受事实约束的内容。</small></span></label><label className="radio-card"><input type="radio" checked={workspace.settings.generation_mode === "api"} onChange={() => update((value) => ({ ...value, settings: { ...value.settings, generation_mode: "api" } }), "已选择 API 模式；缺少密钥时将安全回退。")}/><span><strong>API 模式</strong><small>配置后使用服务端密钥；不可用时自动回退到演示模式。</small></span></label><div className="setting-row"><span><strong>数据持久化</strong><small>{persistence}</small></span><i className={persistence.startsWith("云端") ? "ok" : "neutral"}/></div></article><article className="panel"><div className="panel-title"><div><span>数据导出</span><h2>证据数据包</h2></div></div><p className="setting-copy">下载解决方案、内容资产、审核事件、工作流评测、分析汇总及完整 JSON 工作区。</p><button className="primary wide-button" onClick={exportAll}>导出全部记录</button><div className="file-list">{Object.keys(exportFiles(workspace)).map((name) => <button key={name} onClick={() => download(name, exportFiles(workspace)[name as keyof ReturnType<typeof exportFiles>])}><span>CSV</span>{name}<b>↓</b></button>)}</div></article><article className="panel span-two"><div className="panel-title"><div><span>数据来源</span><h2>原型边界</h2></div></div><div className="boundary-grid"><div><b>已包含</b><p>虚构的智慧城市方案记录、关键角色画像、评估资产、审核事件、复用记录和完整工作流评测观察。</p></div><div><b>未宣称</b><p>不包含数字郑州内部产品数据、真实客户、政府合作关系、CRM 集成、自动发布、政府数据库连接或采购系统集成。</p></div><div><b>未来路径</b><p>完成数据治理与安全评审后，可接入经批准的产品目录、企业身份、CRM 参考信息和发布连接器。</p></div></div><button className="danger-outline" onClick={reset}>重置可复现演示数据</button></article></section></>;
}

export default function Home() {
  const [page, setPage] = useState<Page>("Dashboard"); const [workspace, setWorkspace] = useState<Workspace>(() => buildDemoWorkspace()); const [toast, setToast] = useState(""); const [persistence, setPersistence] = useState("正在检查云端工作区…"); const analytics = useMemo(() => calculateAnalytics(workspace), [workspace]);
  useEffect(() => { let cancelled = false; fetch("/api/state?key=solution-marketing-workspace").then(async (response) => { if (!response.ok) throw new Error(); const payload = await response.json() as { value: unknown }; if (!cancelled && isWorkspace(payload.value)) setWorkspace(payload.value); if (!cancelled) setPersistence("云端 D1 工作区已连接"); }).catch(() => { if (!cancelled) setPersistence("本地演示会话运行中；本地未绑定云数据库"); }); return () => { cancelled = true; }; }, []);
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2800); }
  function update(fn: (value: Workspace) => Workspace, message: string) { setWorkspace((current) => { const next = fn(current); fetch("/api/state", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ key: "solution-marketing-workspace", value: next }) }).then((response) => { if (response.ok) setPersistence("云端 D1 工作区已连接"); }).catch(() => setPersistence("本地演示会话运行中；本地未绑定云数据库")); return next; }); notify(message); }
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">E</div><div><strong>EchoFlow</strong><span>AI 解决方案营销工作台</span></div></div><nav aria-label="主导航"><span className="nav-label">工作区</span>{navItems.map((item) => <button key={item.page} className={page === item.page ? "active" : ""} onClick={() => setPage(item.page)}><i>{item.icon}</i><span>{PAGE_LABELS[item.page]}</span>{item.page === "Review" && <b>{workspace.assets.filter((asset) => asset.review_status === "in_review").length}</b>}</button>)}</nav><div className="sidebar-foot"><div className="mode-card"><span>生成模式</span><strong><i/> {workspace.settings.generation_mode === "demo" ? "演示模式" : "API + 安全回退"}</strong><small>无需密钥即可运行。</small></div><div className="company"><div>DZ</div><span><strong>数字郑州</strong><small>营销技术实习项目</small></span></div></div></aside><main><div className="topbar"><div><span className="crumb">EchoFlow / {PAGE_LABELS[page]}</span><span className="sync"><i/> {persistence}</span></div><div className="top-actions"><button onClick={() => setPage("Analytics")}>评估数据：{workspace.assets.length} 条资产</button><span className="user">EZ</span></div></div><div className="page-content">{page === "Dashboard" && <Dashboard workspace={workspace} analytics={analytics} setPage={setPage}/>} {page === "Solutions" && <SolutionsView workspace={workspace} update={update}/>} {page === "Generate" && <GenerateView workspace={workspace} update={update} setPage={setPage}/>} {page === "Content Library" && <LibraryView workspace={workspace}/>} {page === "Review" && <ReviewView workspace={workspace} update={update}/>} {page === "Analytics" && <AnalyticsView workspace={workspace} analytics={analytics}/>} {page === "Benchmark" && <BenchmarkView workspace={workspace} analytics={analytics} update={update}/>} {page === "Settings" && <SettingsView workspace={workspace} update={update} persistence={persistence}/>}</div></main>{toast && <div className="toast"><span>✓</span>{toast}</div>}</div>;
}
